Memento pattern design
Alex-CG/design-patterns-applications pull request #3
Opened 2018-08-17 04:18 UTC by Alex-CG

2018-08-17 04:31 UTC, miguelReyesC commented on src/main/java/edu/learning/patterns/behavioral/memento/MementoPattern.java
> +
Add getters and setters

2018-08-17 04:31 UTC, miguelReyesC commented on src/main/java/edu/learning/patterns/behavioral/memento/MementoPattern.java
> +class CareTaker {
Add getters and setters

2018-08-17 04:32 UTC, miguelReyesC-zz requested changes
Please improve

2018-08-17 04:56 UTC, miguelReyesC commented
Instale un plugin para que haga code review automatico, fixea lo que te dice :P

2018-08-19 23:41 UTC, miguelReyesC-zz approved these changes

2018-08-19 23:41 UTC, merged